package CreationalUltimateDesignPatterns.abstractFactory.training.buildmuscle;

import CreationalUltimateDesignPatterns.abstractFactory.training.MealPlan;
import CreationalUltimateDesignPatterns.abstractFactory.training.WorkoutPlan;

public class BuildMuscleWorkout implements WorkoutPlan {
}
